USE [MKBBIDW]
GO

/****** Object:  View [dbo].[Test20250515KontoDnReport]    Script Date: 2026-03-16 15:18:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[Test20250515KontoDnReport]
AS
SELECT 
[KontoSK]
      ,[Kontotyp]
      ,K.[KontoNr]
      ,[KontoNamn]
      ,[Konto]
      ,[Konto2Nr]
      ,[Konto2Namn]
      ,[Konto2]
      ,[AltKonto2Nr]
      ,[AltKonto2Namn]
      ,[AltKonto2]
      ,[RrNiv1Nr]
      ,[RrNiv1Namn]
      ,[RrNiv2Nr]
      ,[RrNiv2Namn]
      ,[RrNiv3Nr]
      ,[RrNiv3Namn]
      ,[RrNiv4Nr]
      ,[RrNiv4Namn]
      ,[RrNiv5Nr]
      ,[RrNiv5Namn]
      ,[RrNiv6Nr]
      ,[RrNiv6Namn]
      ,[RrNiv7Nr]
      ,[RrNiv7Namn]
      ,[RrNiv8Nr]
      ,[RrNiv8Namn]
      ,KM.[PNLGroup]
      ,[Brc1Nr]
      ,[Brc1Namn]
      ,[Brc1NamnStyrelserapport]
      ,[Brc2Nr]
      ,[Brc2Namn]
      ,[Brc3Nr]
      ,[Brc3Namn]
      ,[Brc4Nr]
      ,[Brc4Namn]
      ,[BasNorr]
      ,[BasVäst]
      ,[BasÖst]
      ,[BasLokal]
      ,[BasStudent]
      ,[Bas2998]
      ,[BasFörvaltn]
      ,[BasFörvaltnExt]
      ,[BasAUNy]
      ,[BasDrift]
      ,[BasLth]
      ,[BasAdm]
      ,KM.[RRLev1Id]
      ,KM.[RRLev1Namn]
      ,[RRLev1Attr]
      ,KM.[RRLev2Id]
      ,KM.[RRLev2Namn]
      ,[RRLev2Attr]
      ,KM.[RRLev3Id]
      ,KM.[RRLev3Namn]
      ,[RRLev3Attr]
      ,KM.[RRLev4Id]
      ,KM.[RRLev4Namn]
      ,[RRLev4Attr]
      ,KM.[RRLev5Id]
      ,KM.[RRLev5Namn]
      ,[RRLev5Attr]
      ,[Rrkonto_301]
      ,[Rrkonto_301Namn]
      ,[Rrkonto_302]
      ,[Rrkonto_302Namn]
      ,[Brkonto_301]
      ,[Brkonto_301Namn]
      ,[Brkonto_302]
      ,[Brkonto_302namn]
      ,[MalmöStad_Åtgärd301]
      ,[MalmöStadshus_Åtgärd302]
      ,[MalmöStad_Åtgärd301Namn]
      ,[MalmöStadshus_Åtgärd302Namn]
      ,[RrCapego1]
      ,[RrCapego1Namn]
      ,[Br301_Lev1]
      ,[Br301_Lev1Namn]
      ,[Br301_Lev2]
      ,[Br301_Lev2Namn]
      ,[Br301_Lev3]
      ,[Br301_Lev3Namn]
      ,[Br301_Lev4]
      ,[Br301_Lev4Namn]
      ,[Rr301_Lev1]
      ,[Rr301_Lev1Namn]
      ,[Rr301_Lev2]
      ,[Rr301_Lev2Namn]
      ,[Rr301_Lev3]
      ,[Rr301_Lev3Namn]
  FROM [MKBBIDW].[dbo].[ViewDimKonto] K
INNER JOIN TestManKonto20250514 KM ON
	KM.KontoNr = K.KontoNr

UNION ALL

select [KontoSK]
      ,[Kontotyp]
      ,K.[KontoNr]
      ,[KontoNamn]
      ,[Konto]
      ,[Konto2Nr]
      ,[Konto2Namn]
      ,[Konto2]
      ,[AltKonto2Nr]
      ,[AltKonto2Namn]
      ,[AltKonto2]
      ,[RrNiv1Nr]
      ,[RrNiv1Namn]
      ,[RrNiv2Nr]
      ,[RrNiv2Namn]
      ,[RrNiv3Nr]
      ,[RrNiv3Namn]
      ,[RrNiv4Nr]
      ,[RrNiv4Namn]
      ,[RrNiv5Nr]
      ,[RrNiv5Namn]
      ,[RrNiv6Nr]
      ,[RrNiv6Namn]
      ,[RrNiv7Nr]
      ,[RrNiv7Namn]
      ,[RrNiv8Nr]
      ,[RrNiv8Namn]
      ,[PNLGroup]
      ,[Brc1Nr]
      ,[Brc1Namn]
      ,[Brc1NamnStyrelserapport]
      ,[Brc2Nr]
      ,[Brc2Namn]
      ,[Brc3Nr]
      ,[Brc3Namn]
      ,[Brc4Nr]
      ,[Brc4Namn]
      ,[BasNorr]
      ,[BasVäst]
      ,[BasÖst]
      ,[BasLokal]
      ,[BasStudent]
      ,[Bas2998]
      ,[BasFörvaltn]
      ,[BasFörvaltnExt]
      ,[BasAUNy]
      ,[BasDrift]
      ,[BasLth]
      ,[BasAdm]
      ,[RRLev1Id]
      ,[RRLev1Namn]
      ,[RRLev1Attr]
      ,[RRLev2Id]
      ,[RRLev2Namn]
      ,[RRLev2Attr]
      ,[RRLev3Id]
      ,[RRLev3Namn]
      ,[RRLev3Attr]
      ,[RRLev4Id]
      ,[RRLev4Namn]
      ,[RRLev4Attr]
      ,[RRLev5Id]
      ,[RRLev5Namn]
      ,[RRLev5Attr]
      ,[Rrkonto_301]
      ,[Rrkonto_301Namn]
      ,[Rrkonto_302]
      ,[Rrkonto_302Namn]
      ,[Brkonto_301]
      ,[Brkonto_301Namn]
      ,[Brkonto_302]
      ,[Brkonto_302namn]
      ,[MalmöStad_Åtgärd301]
      ,[MalmöStadshus_Åtgärd302]
      ,[MalmöStad_Åtgärd301Namn]
      ,[MalmöStadshus_Åtgärd302Namn]
      ,[RrCapego1]
      ,[RrCapego1Namn]
      ,[Br301_Lev1]
      ,[Br301_Lev1Namn]
      ,[Br301_Lev2]
      ,[Br301_Lev2Namn]
      ,[Br301_Lev3]
      ,[Br301_Lev3Namn]
      ,[Br301_Lev4]
      ,[Br301_Lev4Namn]
      ,[Rr301_Lev1]
      ,[Rr301_Lev1Namn]
      ,[Rr301_Lev2]
      ,[Rr301_Lev2Namn]
      ,[Rr301_Lev3]
      ,[Rr301_Lev3Namn]


from [MKBBIDW].[dbo].[ViewDimKonto] K
where kontonr not in (select kontonr from TestManKonto20250514)


GO


