table Uppföljning
	lineageTag: 2229c9c4-3504-45c3-aa24-a9729fd0007d

	column UppföljningSK
		dataType: int64
		formatString: 0
		lineageTag: 5b098ba7-d2e9-459c-959d-02e6e7c1e785
		summarizeBy: none
		sourceColumn: UppföljningSK

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UppföljningNr
		dataType: string
		lineageTag: 609c77b1-e8bf-44a1-a6a6-3b16c374de52
		summarizeBy: none
		sourceColumn: UppföljningNr

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UppföljningNamn
		dataType: string
		lineageTag: d5a275cb-254d-42c9-9418-c58c12d325da
		summarizeBy: none
		sourceColumn: UppföljningNamn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Uppföljning
		dataType: string
		lineageTag: 92999d75-10d9-46e8-9b5e-3cbe57f178bf
		summarizeBy: none
		sourceColumn: Uppföljning

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Uppföljning2Nr
		dataType: string
		lineageTag: 0ab99479-7054-4830-bad3-40144e74b4f6
		summarizeBy: none
		sourceColumn: Uppföljning2Nr

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Uppföljning2Namn
		dataType: string
		lineageTag: a8a5f1b5-a53b-460a-9d00-a8189373e248
		summarizeBy: none
		sourceColumn: Uppföljning2Namn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Uppföljning2
		dataType: string
		lineageTag: a9be13d1-34a3-4534-bfe8-0c794e204221
		summarizeBy: none
		sourceColumn: Uppföljning2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BasNorr
		dataType: int64
		formatString: 0
		lineageTag: 8267d2a0-3b62-409b-93cb-be69efa6be98
		summarizeBy: none
		sourceColumn: BasNorr

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BasVäst
		dataType: int64
		formatString: 0
		lineageTag: 7c33fd11-e3aa-487f-8b1c-feb243d72283
		summarizeBy: none
		sourceColumn: BasVäst

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BasÖst
		dataType: int64
		formatString: 0
		lineageTag: 007e2a86-0b24-4927-8463-ee18f7fd38f1
		summarizeBy: none
		sourceColumn: BasÖst

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BasLokal
		dataType: int64
		formatString: 0
		lineageTag: cf06c9b0-cf8b-44f6-85b6-ee45fd2ac4bf
		summarizeBy: none
		sourceColumn: BasLokal

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BasStudent
		dataType: int64
		formatString: 0
		lineageTag: e8d608ab-94ac-469a-9aba-e5bfcf029f63
		summarizeBy: none
		sourceColumn: BasStudent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Bas2998
		dataType: int64
		formatString: 0
		lineageTag: 10c8f5da-492f-431d-b38a-543a335dcb1f
		summarizeBy: none
		sourceColumn: Bas2998

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BasFörvaltn
		dataType: int64
		formatString: 0
		lineageTag: 56750d81-b7e5-4946-a949-20dbb0ba5515
		summarizeBy: none
		sourceColumn: BasFörvaltn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BasFörvaltnExt
		dataType: int64
		formatString: 0
		lineageTag: ec4358d0-8959-4031-8c30-97b2ccf6c78a
		summarizeBy: none
		sourceColumn: BasFörvaltnExt

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BasAUNy
		dataType: int64
		formatString: 0
		lineageTag: 4515fcc8-83b4-4e17-962d-7b49de4a8001
		summarizeBy: none
		sourceColumn: BasAUNy

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BasDrift
		dataType: int64
		formatString: 0
		lineageTag: 528767cb-9d29-4375-a6bd-34d51afb17f2
		summarizeBy: none
		sourceColumn: BasDrift

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BasLth
		dataType: int64
		formatString: 0
		lineageTag: a5a501f3-1943-4e7a-9b93-1936267ada15
		summarizeBy: none
		sourceColumn: BasLth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BasAdm
		dataType: int64
		formatString: 0
		lineageTag: c4985598-8ff6-49c8-a919-e3d8460f71f3
		summarizeBy: none
		sourceColumn: BasAdm

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Uppföljning grupp'
		dataType: string
		lineageTag: 2c9f8f2b-da19-432e-a70e-296351d35ac3
		summarizeBy: none
		sourceColumn: Uppföljning grupp

		annotation SummarizationSetBy = Automatic

	column 'Uppföljning grupp VS'
		dataType: string
		lineageTag: 69954015-122d-4246-ba95-94f0098b9ef2
		summarizeBy: none
		sourceColumn: Uppföljning grupp VS

		annotation SummarizationSetBy = Automatic

	column 'Uppföljning grupp BR'
		dataType: string
		lineageTag: 2837cad1-52b7-4260-9a54-70e968983bee
		summarizeBy: none
		sourceColumn: Uppföljning grupp BR

		annotation SummarizationSetBy = Automatic

	partition Uppföljning-cae5658f-13ec-4e4c-bcdb-f8d10f357726 = m
		mode: import
		queryGroup: Dimensionstabeller
		source =
				let
				    Source = Sql.Databases("mkbdw1.mkb.se"),
				    MKBBIDW = Source{[Name="MKBBIDW"]}[Data],
				    dbo_ViewDimUppföljning = MKBBIDW{[Schema="dbo",Item="ViewDimUppföljning"]}[Data],
				    #"Added Custom" = Table.AddColumn(dbo_ViewDimUppföljning, "Uppföljning grupp", each Text.Start([Uppföljning], 2)),
				    #"Added VS" = Table.AddColumn(#"Added Custom", "Uppföljning grupp VS", each if [Uppföljning grupp] = "VS" then "VS" else "Inte VS"),
				    #"Added Custom1" = Table.AddColumn(#"Added VS", "Uppföljning grupp BR", each if [Uppföljning grupp] = "BR" then "BR" else "Inte BR")
				in
				    #"Added Custom1"

	annotation PBI_ResultType = Table

