table FTE
	isHidden
	lineageTag: bc9e5b7c-ecc9-4431-9e2d-970e877c58d4

	column Personalkategori
		dataType: string
		isHidden
		lineageTag: 6831c5af-55cb-4e33-8bfe-6e764ad6403f
		summarizeBy: none
		sourceColumn: Personalkategori

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Admin/Skötsel
		dataType: string
		isHidden
		lineageTag: dea22e9e-692a-4f25-b3fa-0002042da849
		summarizeBy: none
		sourceColumn: Admin/Skötsel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Bemanning
		dataType: string
		isHidden
		lineageTag: 0544bacb-4b75-459f-9587-87013a578afa
		summarizeBy: none
		sourceColumn: Bemanning

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ANST_NR
		dataType: string
		isHidden
		lineageTag: 3d3d1346-e0b8-4276-b21a-a57c33f3ec84
		summarizeBy: none
		sourceColumn: ANST_NR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Namn
		dataType: string
		isHidden
		lineageTag: 946f245e-cbe1-415a-881e-84a6639de045
		summarizeBy: none
		sourceColumn: Namn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ålder nästa år'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b6401459-eb72-468f-99be-a74ae64128c1
		summarizeBy: sum
		sourceColumn: Ålder nästa år

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Månadslön
		dataType: double
		isHidden
		formatString: #,0
		lineageTag: 9cc12d55-a9e3-4909-bb35-4d9f9755fb5b
		summarizeBy: sum
		sourceColumn: Månadslön

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Titel
		dataType: string
		isHidden
		lineageTag: c485681e-a292-4c43-a7b1-f69ca0be09ef
		summarizeBy: none
		sourceColumn: Titel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Tjänstgöringsgrad
		dataType: double
		isHidden
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: eda746a2-7c13-41d8-ae34-1c7b79d99c76
		summarizeBy: sum
		sourceColumn: Tjänstgöringsgrad

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Kostnadsställe
		dataType: string
		isHidden
		lineageTag: ef2aa8ec-e8e8-4009-89a4-ea71823c377b
		summarizeBy: none
		sourceColumn: Kostnadsställe

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Antal månader nästa år'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 83202f9d-f584-4763-8e6e-ac9d43102aed
		summarizeBy: sum
		sourceColumn: Antal månader nästa år

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AVGANGSDATUM
		dataType: string
		isHidden
		lineageTag: d68ac1eb-e70f-4c45-8eac-c18bd7aa50e6
		summarizeBy: none
		sourceColumn: AVGANGSDATUM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Antal FTE'
		dataType: double
		isHidden
		lineageTag: 3fdad8b6-f36c-44f1-8796-d82e7270d078
		summarizeBy: sum
		sourceColumn: Antal FTE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tidigare lön'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 76930d6e-af3c-42b6-8d4f-e92199b97cc2
		summarizeBy: sum
		sourceColumn: Tidigare lön

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FODELSEDATUM
		dataType: string
		isHidden
		lineageTag: d3fce618-9222-4c2f-b787-04fb279bd17d
		summarizeBy: none
		sourceColumn: FODELSEDATUM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ANSTALLNINGSDATUM
		dataType: string
		isHidden
		lineageTag: e9a2d780-85e1-491b-ae86-02c73ec1a33a
		summarizeBy: none
		sourceColumn: ANSTALLNINGSDATUM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Tillägg 230'
		dataType: double
		isHidden
		formatString: #,0
		lineageTag: 3def3653-2f35-41a6-a512-4b4be113e389
		summarizeBy: sum
		sourceColumn: Tillägg 230

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Tillägg 230 antal månader nästa år'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 96417f63-ad17-4d03-8d55-90480a88cbd5
		summarizeBy: sum
		sourceColumn: Tillägg 230 antal månader nästa år

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Anpassad
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 4a8af122-3227-4df3-885e-a7f2609f539b
		summarizeBy: none
		sourceColumn: Anpassad

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FTE = m
		mode: import
		source =
				let
				    Källa = Sql.Databases("mkbdw1.mkb.se"),
				    MKBBIDW = Källa{[Name="MKBBIDW"]}[Data],
				    dbo_ViewDimFTE = MKBBIDW{[Schema="dbo",Item="ViewDimFTE"]}[Data],
				    #"Lägg till egen" = Table.AddColumn(dbo_ViewDimFTE, "Anpassad", each if [AVGANGSDATUM] = null then Date.From(DateTime.LocalNow()) else Date.From([AVGANGSDATUM]))
				in
				    #"Lägg till egen"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigering

	annotation PBI_ResultType = Table

