table Anställningar_Hashed
	lineageTag: 17a7c98f-8274-4cd3-9d9f-e882c0cce55d

	column AnställningsnummerHashed
		dataType: string
		lineageTag: c12542a3-ff82-4c19-a371-15455ee9642e
		summarizeBy: none
		sourceColumn: AnställningsnummerHashed

		annotation SummarizationSetBy = Automatic

	column GiltigFrån
		dataType: dateTime
		formatString: Long Date
		lineageTag: dbbf2e3d-c69b-4c62-9a13-e527a508e3c3
		summarizeBy: none
		sourceColumn: GiltigFrån

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column GiltigTill
		dataType: dateTime
		formatString: Long Date
		lineageTag: 349ae4fe-a428-48f2-87f3-ac80b3f994d9
		summarizeBy: none
		sourceColumn: GiltigTill

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Sysselsättningsgrad
		dataType: double
		lineageTag: 70301462-980a-4b16-9be7-ff04f3113b76
		summarizeBy: sum
		sourceColumn: Sysselsättningsgrad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HeltidDeltid
		dataType: string
		lineageTag: 805b9877-7e9b-4301-b682-8150f8424437
		summarizeBy: none
		sourceColumn: HeltidDeltid

		annotation SummarizationSetBy = Automatic

	column Veckoarbetstid
		dataType: double
		lineageTag: ad307537-4cd9-4d7c-a6ec-f32768d9d337
		summarizeBy: sum
		sourceColumn: Veckoarbetstid

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AnställningsformId
		dataType: int64
		formatString: 0
		lineageTag: a94e7333-2d1c-42b8-bd16-f8d1ce95e393
		summarizeBy: count
		sourceColumn: AnställningsformId

		annotation SummarizationSetBy = Automatic

	column Avgångsorsak
		dataType: string
		lineageTag: 85a9f1fa-69ce-4c54-9aee-223f79426583
		summarizeBy: none
		sourceColumn: Avgångsorsak

		annotation SummarizationSetBy = Automatic

	partition Anställningar_Hashed-63cc62ad-a6fb-48e1-92d4-f4513f67976c = m
		mode: import
		source =
				let
				    Source = Sql.Databases("mkbdw1.mkb.se"),
				    MKBBIDW = Source{[Name="MKBBIDW"]}[Data],
				    dbo_viewFactAnställningar_Hashed = MKBBIDW{[Schema="dbo",Item="viewFactAnställningar_Hashed"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_viewFactAnställningar_Hashed,{{"AnställningsnummerHashed", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigering

