table Frånvaro
	lineageTag: 06b0881d-e652-4697-b461-76b33c21e0fc

	column TimeSK
		dataType: string
		lineageTag: 970581e3-27e4-45ad-82f7-b3808dd5093c
		summarizeBy: none
		sourceColumn: TimeSK

		annotation SummarizationSetBy = Automatic

	column Datum
		dataType: dateTime
		formatString: Long Date
		lineageTag: 23e52240-8a68-4a51-af7b-5546b9d9ec7d
		summarizeBy: none
		sourceColumn: Datum

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Fomdatum
		dataType: dateTime
		formatString: Short Date
		lineageTag: b3cece5c-08ba-48ec-b29b-1ac432f4ff43
		summarizeBy: none
		sourceColumn: Fomdatum

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Tomdatum
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5ecc683d-7de1-404b-9430-2b0ae8b2564a
		summarizeBy: none
		sourceColumn: Tomdatum

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Anstnr
		dataType: int64
		formatString: 0
		lineageTag: f42435ac-89a2-4b23-9989-5cc709bda934
		summarizeBy: none
		sourceColumn: Anstnr

		annotation SummarizationSetBy = Automatic

	column Kortkod
		dataType: string
		lineageTag: d0fcd66b-06be-49f8-94b9-de44800f6e24
		summarizeBy: none
		sourceColumn: Kortkod

		annotation SummarizationSetBy = Automatic

	column Orsak
		dataType: string
		lineageTag: 53515c16-49e0-480c-b538-5f48fbdf3e0a
		summarizeBy: none
		sourceColumn: Orsak

		annotation SummarizationSetBy = Automatic

	column Procent
		dataType: double
		lineageTag: ac21afae-518f-4543-a70f-1c8e846ed3a0
		summarizeBy: sum
		sourceColumn: Procent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Arbetsdagar
		dataType: int64
		formatString: 0
		lineageTag: 9738dd38-7855-4f6a-8054-caf9b2389c45
		summarizeBy: sum
		sourceColumn: Arbetsdagar

		annotation SummarizationSetBy = Automatic

	column Kalenderdagar
		dataType: int64
		formatString: 0
		lineageTag: 70c322be-f99e-4c58-9c62-fa371c123cc0
		summarizeBy: sum
		sourceColumn: Kalenderdagar

		annotation SummarizationSetBy = Automatic

	column Sjuktyp
		dataType: int64
		formatString: 0
		lineageTag: fd5987cc-3d59-4f74-9e6b-3fc12032b7c1
		summarizeBy: none
		sourceColumn: Sjuktyp

		annotation SummarizationSetBy = Automatic

	column Sjukskrivningstyp
		dataType: string
		lineageTag: 109a8543-dea5-427b-93db-45e12a683a52
		summarizeBy: none
		sourceColumn: Sjukskrivningstyp

		annotation SummarizationSetBy = Automatic

	column 'Antal Dagar Sjukskriven'
		dataType: double
		lineageTag: 635aad0f-43cd-4d3c-a8d0-caed14ef2ea5
		summarizeBy: sum
		sourceColumn: Antal Dagar Sjukskriven

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Frånvaro = m
		mode: import
		source =
				let
				    Source = Sql.Databases("mkbdw1.mkb.se"),
				    MKBBIDW = Source{[Name="MKBBIDW"]}[Data],
				    dbo_viewFactFrånvaro = MKBBIDW{[Schema="dbo",Item="viewFactFrånvaro"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_viewFactFrånvaro,{{"Fomdatum", type date}, {"Tomdatum", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigering

