table JobbKlassificering
	lineageTag: e0297dd3-8c1d-42de-a085-ace14ba0ebe6

	column Klassificering
		dataType: string
		lineageTag: 94dc1cfb-ba2e-44c8-a7ec-225fc3ca383d
		summarizeBy: none
		sourceColumn: Klassificering

		annotation SummarizationSetBy = Automatic

	column KlassificeringsId
		dataType: int64
		formatString: 0
		lineageTag: ae63ef34-d924-49a7-bc61-40f077dc5dcc
		summarizeBy: none
		sourceColumn: KlassificeringsId

		annotation SummarizationSetBy = Automatic

	partition JobbKlassificering = m
		mode: import
		source =
				let
				    Källa = Sql.Database("mkbdw1.mkb.se", "MKBBIDW"),
				    dim_KlassificeringFeriejobb = Källa{[Schema="dim",Item="KlassificeringFeriejobb"]}[Data],
				    #"Filtrerade rader" = Table.SelectRows(dim_KlassificeringFeriejobb, each ([Klassificering] <> "Exterm"))
				in
				    #"Filtrerade rader"

	annotation PBI_NavigationStepName = Navigering

	annotation PBI_ResultType = Table

