table Timanställningar
	lineageTag: a8c2ca57-f8a9-40fd-b131-485ce6a851c6

	column Anställningsnummer
		dataType: int64
		formatString: 0
		lineageTag: ac6cff5e-43ba-4561-9419-505c2ea96d4e
		summarizeBy: none
		sourceColumn: Anställningsnummer

		annotation SummarizationSetBy = Automatic

	column Löneartid
		dataType: int64
		formatString: 0
		lineageTag: e8d38dba-5252-434f-b587-5cdba8c2ac25
		summarizeBy: sum
		sourceColumn: Löneartid

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: dateTime
		formatString: Long Date
		lineageTag: f3a3f31f-bb5e-449d-a947-629ab73d69c3
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Antal
		dataType: double
		lineageTag: a1978b7a-5273-49aa-b240-46b81f709225
		summarizeBy: sum
		sourceColumn: Antal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AnställningsformID
		dataType: string
		lineageTag: a0fd4a9e-72ae-47db-93ac-fce5856ba41b
		summarizeBy: none
		sourceColumn: AnställningsformID

		annotation SummarizationSetBy = Automatic

	partition Timanställningar-8912dfa5-09ea-4146-a308-a31b7a1a4111 = m
		mode: import
		source =
				let
				    Source = Sql.Databases("mkbdw1.mkb.se"),
				    MKBBIDW = Source{[Name="MKBBIDW"]}[Data],
				    dbo_viewFactTimanställningar = MKBBIDW{[Schema="dbo",Item="viewFactTimanställningar"]}[Data],
				    #"Added Custom" = Table.AddColumn(dbo_viewFactTimanställningar, "AnställningsformID", each -99)
				in
				    #"Added Custom"

	annotation PBI_ResultType = Table

