table ViewDimAnstalldAldersIntervall
	lineageTag: 807c0cfd-f74e-4cf8-a54b-2584cf7decb1

	column AldersIntervallId
		dataType: int64
		formatString: 0
		lineageTag: e14612cc-23d3-42b7-88ca-611b25c2802c
		summarizeBy: count
		sourceColumn: AldersIntervallId

		annotation SummarizationSetBy = Automatic

	column Åldersintervall
		dataType: string
		lineageTag: fc4065df-3ed6-4af6-90d6-c9b9577ff1f2
		summarizeBy: none
		sourceColumn: Åldersintervall
		sortByColumn: AldersIntervallId

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition ViewDimAnstalldAldersIntervall = m
		mode: import
		source =
				let
				    Source = Sql.Databases("mkbdw1.mkb.se"),
				    MKBBIDW = Source{[Name="MKBBIDW"]}[Data],
				    dbo_ViewDimAnstalldAldersIntervall = MKBBIDW{[Schema="dbo",Item="ViewDimAnstalldAldersIntervall"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dbo_ViewDimAnstalldAldersIntervall,{{"AldersIntervall", "Åldersintervall"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

